//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBurger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public int Usuario_Id { get; set; }
        public int Hamburguesa_Id { get; set; }
        public int Estado_Id { get; set; }
        public decimal Total { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Hamburguesa Hamburguesa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
